services:
  catalogdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: catalogdb_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  orderingdb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderingdb_container
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password123!
    ports:
      - "1434:1433"
    volumes:
      - ordervolume:/var/opt/mssql

volumes:
  sqlvolume:
  ordervolume: